### ISSUE TITLE
No video in iOS

### ISSUE THREAD

**Issue by Fyb3roptik** [nchutchind/Streaming-Media-Cordova-Plugin#18]
Tested in iOS 6, 7 and 8. No video only audio. Controls do nothing and I have to force close app. Need this fixed ASAP or else I have to find another plugin

**Comment by Adamatt** [comment]
Tested in iOS 6,7 and 8 and everything works correctly dude, make sure you use it the right way

**Comment by Fyb3roptik** [comment]
Yeah I had it playing twice. Was user error! =P
