### ISSUE TITLE
ios build failed when plugin added

### ISSUE THREAD

**Issue by yzargari** [nchutchind/Streaming-Media-Cordova-Plugin#40]
Hi guys,

I'm able to build my app for Android with the plugin and it works beautifully. Building for iOS, however, fails with the below message.

I have the latest plugin (0.1.4), latest cordova-ios (4.0.1), latest PhoneGap cli (5.3.9), latest OSX (El Capitan 10.11.3) and latest Xcode (7.2).

Any idea what I might be doing wrong?

Thanks,
Joseph

/Users/joseph/Desktop/myproject/platforms/ios/myproject/Plugins/com.hutchind.cordova.plugins.streamingmedia/StreamingMedia.m:31:33: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
        self = (StreamingMedia*)[super initWithWebView:theWebView];
                                 ~~~~~ ^~~~~~~~~~~~~~~
/Users/joseph/Desktop/myproject/platforms/ios/myproject/Plugins/com.hutchind.cordova.plugins.streamingmedia/StreamingMedia.m:49:24: warning: incompatible integer to pointer conversion assigning to 'BOOL *' (aka 'signed char *') from 'signed char _Nullable' [-Wint-conversion]
        initFullscreen = [[options objectForKey:@"initFullscreen"] boolValue];
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/joseph/Desktop/myproject/platforms/ios/myproject/Plugins/com.hutchind.cordova.plugins.streamingmedia/StreamingMedia.m:51:24: warning: incompatible integer to pointer conversion assigning to 'BOOL *' (aka 'signed char *') from 'int' [-Wint-conversion]
        initFullscreen = true;
                       ^ ~~~~
2 warnings and 1 error generated.



** BUILD FAILED **


The following build commands failed:

	CompileC build/myproject.build/Debug-iphonesimulator/myproject.build/Objects-normal/i386/StreamingMedia.o myproject/Plugins/com.hutchind.cordova.plugins.streamingmedia/StreamingMedia.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/joseph/Desktop/myproject/platforms/ios/cordova/build-debug.xcconfig,-project,myproject.xcodeproj,ARCHS=i386,-target,myproject,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/joseph/Desktop/myproject/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/joseph/Desktop/myproject/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/joseph/Desktop/myproject/platforms/ios/cordova/build-debug.xcconfig,-project,myproject.xcodeproj,ARCHS=i386,-target,myproject,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/joseph/Desktop/myproject/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/joseph/Desktop/myproject/platforms/ios/build/sharedpch

**Comment by mluria** [comment]
I'm seeing the same problem.  

I saw this link that they were having a similar problem in the KeychainPlugin
https://github.com/shazron/KeychainPlugin/issues/21

They also reference:

https://github.com/AllJoyn-Cordova/cordova-chat-alljoyn/issues/4

It seem that initwithWebView is no longer needed in cordova-ios 4.0 and this causes an error.  

In KeychainPlugin, it seems that the fix is to just comment out the whole function.

I tried that here, and it seemed to work for me, but I'm really not that familiar with ios programming, so I didn't fork the repository, but maybe the maintainer can try this fix out.

**Comment by yzargari** [comment]
@mluria thanks for the tip. I'm even less of an iOS programmer myself, so I wouldn't have tried that... I can confirm this solved my problem too, builds nicely and even works on a real device :)

@nchutchind can you confirm the solution @mluria made is correct? Will you be committing this change to your code?

**Comment by mluria** [comment]
it looks like @nchutchind is no longer maintaining this code.

**Comment by mindhells** [comment]
I've created a pull request to solve this problem, as indicated here in this issue: #44

**Comment by bcolflesh** [comment]
@nchutchind - please approve the change

**Comment by bcolflesh** [comment]
Or someone who understands this better than me fork and publish to npm
