### ISSUE TITLE
Repository Status is now "Unmaintained"

### ISSUE THREAD

**Issue by nchutchind** [nchutchind/Streaming-Media-Cordova-Plugin#42]
This issue is so that watchers will receive a notification.

I developed this plugin while working at a job on a project that needed streaming media. A year ago, I left that job and have not had a need (or the time) to revisit this plugin, which is why there have been no updates. I would love to see someone fork this repo and build it up into something that the community can continue to use, but I just do not have the ability to do that myself now.

**Comment by faceleg** [comment]
Add me as a contributor if you want me to help manage issues / merge acceptable PR's.
